name: Build for Linux

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenBLAS Version to Build'
        required: true
        default: 'v0.3.27'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openmp: [0, 1]
        target: [HASWELL, ARMV8]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: OpenMathLib/OpenBLAS
          ref: ${{ github.event.inputs.version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc gfortran libopenblas-dev liblapack-dev cmake

      - name: Build OpenBLAS
        id: builder
        run: |
          if [[ "${{ matrix.openmp }}" -eq 0 ]]; then
            echo "OPENMP_SUFFIX=serial" >> "$GITHUB_OUTPUT"
            export OPENMP_SUFFIX="serial"
          else
            echo "OPENMP_SUFFIX=openmp" >> "$GITHUB_OUTPUT"
            export OPENMP_SUFFIX="openmp"
          fi
          
          if [[ "${{ matrix.target }}" == "HASWELL" ]]; then
            echo "TARGET_SUFFIX=x86_64" >> "$GITHUB_OUTPUT"
            export TARGET_SUFFIX="x86_64"
          else
            echo "TARGET_SUFFIX=armv8" >> "$GITHUB_OUTPUT"
            export TARGET_SUFFIX="armv8"
          fi
          
          make -j$(nproc) DYNAMIC_ARCH=1 USE_OPENMP=${{ matrix.openmp }} TARGET=${{ matrix.target }} NUM_THREADS=64 ONLY_CBLAS=1 libs shared
          make PREFIX=$PWD/openblas-${OPENMP_SUFFIX}-${TARGET_SUFFIX} install

      - name: Compress to Tarball
        run: |
          tar -czvf openblas-${{ steps.builder.outputs.OPENMP_SUFFIX }}-${{ steps.builder.outputs.TARGET_SUFFIX }}.tar.gz openblas-${{ steps.builder.outputs.OPENMP_SUFFIX }}-${{ steps.builder.outputs.TARGET_SUFFIX }}

      - name: Upload OpenBLAS
        uses: actions/upload-artifact@v4
        with:
          name: openblas-linux-${{ steps.builder.outputs.OPENMP_SUFFIX }}-${{ steps.builder.outputs.TARGET_SUFFIX }}-${{ github.event.inputs.version }}
          path: ${{ github.workspace }}/*.tar.gz
