name: Build for macOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenBLAS Version to Build (e.g. v0.3.27)'
        required: true
        default: 'v0.3.27'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        openmp: [0, 1]
        target: [VORTEX, NEHALEM]


    steps:
    - name: Checkout Repository
      with:
        repository: OpenMathLib/OpenBLAS
        ref: ${{ github.event.inputs.version }}
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew reinstall gcc
        brew install coreutils cmake
        brew install llvm

    - name: Build OpenBLAS
      id: builder
      run: |
        if [[ "${{matrix.openmp}}" -eq 0 ]]; then
            echo "OPENMP_SUFFIX=serial" >> "$GITHUB_OUTPUT"
        else
            echo "OPENMP_SUFFIX=openmp" >> "$GITHUB_OUTPUT"
        fi

        if [[ "${{matrix.target}}" == "VORTEX" ]]; then
            echo "TARGET_SUFFIX=arm64" >> "$GITHUB_OUTPUT"
        else
            echo "TARGET_SUFFIX=x86_64" >> "$GITHUB_OUTPUT"
        fi
        
        
        export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
        export CC="/opt/homebrew/opt/llvm/bin/clang"
        make -j$(nproc) DYNAMIC_ARCH=1 USE_OPENMP=${{matrix.openmp}} TARGET=${{matrix.target}} NUM_THREADS=56 FC=gfortran libs netlib shared
        make PREFIX=$PWD/openblas-${OPENMP_SUFFIX}-${TARGET_SUFFIX} install

    - name: Compress to Tarball
      id: compressor
      run: |
        tar -czvf openblas-${{ steps.builder.outputs.OPENMP_SUFFIX }}-${{ steps.builder.outputs.TARGET_SUFFIX }}.tar.gz openblas-${{ steps.builder.outputs.OPENMP_SUFFIX }}-${{ steps.builder.outputs.TARGET_SUFFIX }}

    - name: Upload OpenBLAS
      uses: actions/upload-artifact@v4
      with:
        name: openblas-${{ steps.compressor.outputs.OPENMP_SUFFIX }}-${{ steps.compressor.outputs.TARGET_SUFFIX }}-{{ github.event.inputs.version }}
        path: ${{ github.workspace }}/*.tar.gz

