name: Build for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        openmp: [0, 1]
        target: [VORTEX, NEHALEM]


    steps:
    - name: Checkout Repository
      with:
        repository: OpenMathLib/OpenBLAS
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew reinstall gcc
        brew install coreutils cmake
        brew install llvm

    - name: Build OpenBLAS
      run: |
        export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
        export CC="/opt/homebrew/opt/llvm/bin/clang"
        make -j$(nproc) DYNAMIC_ARCH=1 USE_OPENMP=${{matrix.openmp}} TARGET=${{matrix.target}} FC=gfortran
        make PREFIX=$PWD/install install 

    - name: Save OpenBLAS
      uses: actions/upload-artifact@v4
      with:
        name: openblas-${{matrix.openmp}}-${{matrix.target}}
        path: install

