name: Build for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        openmp: [0, 1]
        target: [VORTEX, NEHALEM]


    steps:
    - name: Checkout Repository
      with:
        repository: OpenMathLib/OpenBLAS
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew reinstall gcc
        brew install coreutils cmake
        brew install llvm

    - name: Build OpenBLAS
      run: |
        export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
        export CC="/opt/homebrew/opt/llvm/bin/clang"
        make -j$(nproc) DYNAMIC_ARCH=1 USE_OPENMP=${{matrix.openmp}} TARGET=${{matrix.target}} FC=gfortran
        make PREFIX=$PWD/install install 

    - name: Compress to Tarball
      run: |
        # Determine the appropriate suffixes based on openmp and target values
        if [[ "${{matrix.openmp}}" -eq 0 ]]; then
            echo "OPENMP_SUFFIX=serial" >> "$GITHUB_ENV"
        else
            echo "OPENMP_SUFFIX=openmp" >> "$GITHUB_ENV"
        fi

        if [[ "${{matrix.target}}" == "VORTEX" ]]; then
            echo "TARGET_SUFFIX=arm64" >> "$GITHUB_ENV"
        else
            echo "TARGET_SUFFIX=x86_64" >> "$GITHUB_ENV"
        fi

        # Combine suffixes and create the artifact filename
        filename="openblas-${OPENMP_SUFFIX}-${TARGET_SUFFIX}.tar.gz"

        # Compress the install directory
        tar -czvf "$filename" install

    - name: Upload OpenBLAS
      uses: actions/upload-artifact@v4
      with:
        name: openblas-"$OPENMP_SUFFIX"-"$TARGET_SUFFIX"
        path: openblas-"$OPENMP_SUFFIX"-"$TARGET_SUFFIX".tar.gz

