name: Build for Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenBLAS Version to Build'
        required: true
        default: 'v0.3.27'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        openmp: [OFF, ON]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: OpenMathLib/OpenBLAS
          ref: ${{ github.event.inputs.version }}

      - name: Install Build Dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          release: false  # Use pre-installed version
          install: >-
            base-devel
            mingw-w64-ucrt-x86_64-cc
            mingw-w64-ucrt-x86_64-fc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-ccache

      - name: Configure OpenBLAS
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_SHARED_LIBS=ON \
              -DBUILD_STATIC_LIBS=ON \
              -DDYNAMIC_ARCH=ON \
              -DUSE_OPENMP=${{ matrix.openmp }} \
              -DUSE_THREAD=ON \
              -DNUM_THREADS=64 \
              -DTARGET=CORE2 \
              -DBINARY=64 -DINTERFACE64=1 \
              ..

      - name: Build OpenBLAS
        run: |
          cd build && cmake --build .
          cmake --install . --prefix install
          ccache -s

      - name: Compress to Tarball
        id: compressor
        run: |
          if [[ "${{ matrix.openmp }}" -eq OFF ]]; then
            echo "OPENMP_SUFFIX=serial" >> "$GITHUB_OUTPUT"
            export OPENMP_SUFFIX="serial"
          else
            echo "OPENMP_SUFFIX=openmp" >> "$GITHUB_OUTPUT"
            export OPENMP_SUFFIX="openmp"
          fi
          
          tar -czvf openblas-windows-${OPENMP_SUFFIX}.tar.gz build/install

      - name: Upload OpenBLAS
        uses: actions/upload-artifact@v4
        with:
            name: openblas-windows-${{ steps.compressor.outputs.OPENMP_SUFFIX }}-${{ github.event.inputs.version }}
            path: ${{ github.workspace }}/*.tar.gz
