name: Build for Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenBLAS Version to Build'
        required: true
        default: 'v0.3.27'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        openmp: [0, 1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: OpenMathLib/OpenBLAS
          ref: ${{ github.event.inputs.version }}

      - name: Install Dependencies
        run: |
          choco install -y msys2
          refreshenv
          
          # Update msys2 and install dependencies
          msys2 -c 'pacman -Syu --noconfirm'
          msys2 -c 'pacman -S --noconfirm gcc-fortran make'
          
          # Create symbolic links for the gcc and gfortran binaries
          ln -s /mingw64/bin/gcc.exe /usr/bin/gcc
          ln -s /mingw64/bin/gfortran.exe /usr/bin/gfortran

      - name: Build OpenBLAS
        id: builder
        run: |
          if [[ "${{ matrix.openmp }}" -eq 0 ]]; then
            echo "OPENMP_SUFFIX=serial" >> "$GITHUB_OUTPUT"
            export OPENMP_SUFFIX="serial"
          else
            echo "OPENMP_SUFFIX=openmp" >> "$GITHUB_OUTPUT"
            export OPENMP_SUFFIX="openmp"
          fi
          
          make -j$(nproc) DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 USE_OPENMP=${{ matrix.openmp }} TARGET=GENERIC NUM_THREADS=64 CONSISTENT_FPCSR=1libs netlib shared
          make PREFIX=$PWD/openblas-${{ steps.builder.outputs.OPENMP_SUFFIX }} install

      - name: Compress to Tarball
        run: |
          tar -czvf openblas-${{ steps.builder.outputs.OPENMP_SUFFIX }}.tar.gz openblas-${{ steps.builder.outputs.OPENMP_SUFFIX }}

      - name: Upload OpenBLAS
        uses: actions/upload-artifact@v4
        with:
          name: openblas-windows-${{ steps.builder.outputs.OPENMP_SUFFIX }}-${{ github.event.inputs.version }}
          path: ${{ github.workspace }}/*.tar.gz
